In [1]:
#!/usr/bin/python

import sys
import pickle
sys.path.append("../tools/")

from feature_format import featureFormat, targetFeatureSplit
from tester import dump_classifier_and_data

### Task 1: Select what features you'll use.
### features_list is a list of strings, each of which is a feature name.
### The first feature must be "poi".
features_list = ['poi','salary', 'deferral_payments', 'total_payments',
                 'loan_advances', 'bonus', 'restricted_stock_deferred',
                 'deferred_income', 'total_stock_value', 'expenses',
                 'exercised_stock_options', 'other', 'long_term_incentive',
                 'restricted_stock', 'director_fees'] 

# You will need to use more features

### Load the dictionary containing the dataset
with open("final_project_dataset.pkl", "r") as data_file:
    data_dict = pickle.load(data_file)

**Only 146 datapoints**

'LOCKHART EUGENE E' has all features zero 


there are lots of NaNs! (considering only monetary features)
    * only one parson has 1 one feature missing
    * 11 have only 2 features
    
18 is POI and 128 is NOT

## Explore data set

In [12]:
my_dataset = data_dict


count_y = 0
count_n = 0

name_to_index = {}

for idx, person in enumerate(data_dict.keys()):
    name_to_index[person] = idx
    
    allzero = True
    
    if data_dict[person]['poi'] == 'NaN':
        print person  
    elif data_dict[person]['poi']:
        count_y +=1
    else:
        count_n +=1
        
    for val in ['salary', 'deferral_payments', 'total_payments',
                 'loan_advances', 'bonus', 'restricted_stock_deferred',
                 'deferred_income', 'total_stock_value', 'expenses',
                 'exercised_stock_options', 'other', 'long_term_incentive',
                 'restricted_stock', 'director_fees']:
        
#         if data_dict[person][val] == 'NaN' or data_dict[person][val] >0:
#             allzero = False
#             break

        if data_dict[person][val] == 'NaN':
            #print person
            #print str(val) +" NaN"
            data_dict[person][val] = 0

#         if data_dict[person][val] < 0:
#             print person
#             print str(val) +" "+str(data_dict[person][val])
#             data_dict[person][val] = -1
  
#     if allzero == True:
#         print person
print "yes"
print count_y

print "no"
print count_n

print data_dict['TOTAL']
data_dict['LOCKHART EUGENE E']

yes
18
no
128
{'salary': 26704229, 'to_messages': 'NaN', 'deferral_payments': 32083396, 'total_payments': 309886585, 'exercised_stock_options': 311764000, 'bonus': 97343619, 'restricted_stock': 130322299, 'shared_receipt_with_poi': 'NaN', 'restricted_stock_deferred': -7576788, 'total_stock_value': 434509511, 'expenses': 5235198, 'loan_advances': 83925000, 'from_messages': 'NaN', 'other': 42667589, 'from_this_person_to_poi': 'NaN', 'poi': False, 'director_fees': 1398517, 'deferred_income': -27992891, 'long_term_incentive': 48521928, 'email_address': 'NaN', 'from_poi_to_this_person': 'NaN'}


{'bonus': 0,
 'deferral_payments': 0,
 'deferred_income': 0,
 'director_fees': 0,
 'email_address': 'NaN',
 'exercised_stock_options': 0,
 'expenses': 0,
 'from_messages': 'NaN',
 'from_poi_to_this_person': 'NaN',
 'from_this_person_to_poi': 'NaN',
 'loan_advances': 0,
 'long_term_incentive': 0,
 'other': 0,
 'poi': False,
 'restricted_stock': 0,
 'restricted_stock_deferred': 0,
 'salary': 0,
 'shared_receipt_with_poi': 'NaN',
 'to_messages': 'NaN',
 'total_payments': 0,
 'total_stock_value': 0}

In [3]:
print name_to_index['TOTAL']

print data_dict['TOTAL']

print len(data_dict)
data_dict['LOCKHART EUGENE E']

backup_dict = data_dict

len(data_dict)

104
{'salary': 26704229, 'to_messages': 'NaN', 'deferral_payments': 32083396, 'total_payments': 309886585, 'exercised_stock_options': 311764000, 'bonus': 97343619, 'restricted_stock': 130322299, 'shared_receipt_with_poi': 'NaN', 'restricted_stock_deferred': -7576788, 'total_stock_value': 434509511, 'expenses': 5235198, 'loan_advances': 83925000, 'from_messages': 'NaN', 'other': 42667589, 'from_this_person_to_poi': 'NaN', 'poi': False, 'director_fees': 1398517, 'deferred_income': -27992891, 'long_term_incentive': 48521928, 'email_address': 'NaN', 'from_poi_to_this_person': 'NaN'}
146


146

In [4]:
### Task 2: Remove outliers
### Task 3: Create new feature(s)
### Store to my_dataset for easy export below.
#del data_dict[""]
#del data_dict[]

my_dataset = data_dict


import numpy as np

### Extract features and labels from dataset for local testing
data = featureFormat(my_dataset, features_list, sort_keys = False,
                    remove_all_zeroes=False, remove_any_zeroes=False)
labels, features = targetFeatureSplit(data)

## investigate a bit
print data.shape

cols_z = (data == 0).sum(0)
print cols_z #np.sort(rows_z)

cols_n = (data < -1).sum(0)
print cols_n #np.sort(rows_z)

cols_p = (data >0).sum(0)
print cols_p

index = name_to_index['TOTAL']

print data_dict['TOTAL'][features_list[2]]
print data[index,2]

#print rows
#rows_n = (data < 0).sum(1)
#print rows_n #np.sort(rows_n)


# cols_v = (data > 0).sum(0)
# print cols_v
# #print rows_v #np.sort(rows_v)

# print (cols_z + cols_v)

#cols = (data == 0).sum(0)
#print cols

#print np.sort(cols)
#print np.where(cols == 142)



#print [20,  21,  36,  44,  51,  51,  53]

#print [features_list[i] for i in [8,3,13,10,1,9,11]]


(146, 15)
[128  51 107  21 142  64 128  97  20  51  44  53  80  36 129]
[ 0  0  1  0  0  0 16 49  1  0  0  0  0  1  0]
[ 18  95  38 125   4  82   2   0 125  95 102  93  66 109  17]
32083396
32083396.0


In [5]:
rows_n = (data == 0).sum(1)
print np.sort(rows_n)
print np.median(rows_n)


[ 1  2  3  3  3  3  3  4  4  4  4  4  4  4  5  5  5  5  5  5  5  5  5  5  5
  5  5  5  5  5  5  5  5  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6
  6  6  6  6  6  6  6  6  6  6  6  6  6  7  7  7  7  7  7  7  7  7  7  7  7
  7  7  7  7  8  8  8  8  8  8  8  8  8  8  8  8  9  9  9  9  9 10 10 10 10
 10 10 10 10 10 10 10 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 12 12 12
 12 12 12 12 12 12 12 12 12 13 13 13 13 13 13 13 13 13 13 13 15]
7.0


## Train Classifier

In [15]:
### Task 4: Try a varity of classifiers
### Please name your classifier clf for easy export below.
### Note that if you want to do PCA or other multi-stage operations,
### you'll need to use Pipelines. For more info:
### http://scikit-learn.org/stable/modules/pipeline.html

# Provided to give you a starting point. Try a variety of classifiers.
from sklearn import tree
clf = tree.DecisionTreeClassifier()

In [7]:
### Task 4: Try a varity of classifiers
### Please name your classifier clf for easy export below.
### Note that if you want to do PCA or other multi-stage operations,
### you'll need to use Pipelines. For more info:
### http://scikit-learn.org/stable/modules/pipeline.html

# Provided to give you a starting point. Try a variety of classifiers.
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()


In [16]:
### Task 5: Tune your classifier to achieve better than .3 precision and recall 
### using our testing script. Check the tester.py script in the final project
### folder for details on the evaluation method, especially the test_classifier
### function. Because of the small size of the dataset, the script uses
### stratified shuffle split cross validation. For more info: 
### http://scikit-learn.org/stable/modules/generated/sklearn.cross_validation.StratifiedShuffleSplit.html

# Example starting point. Try investigating other evaluation techniques!
from sklearn.cross_validation import train_test_split

features_train, features_test, labels_train, labels_test = \
    train_test_split(features, labels, test_size=0.3, random_state=42)

### Task 6: Dump your classifier, dataset, and features_list so anyone can
### check your results. You do not need to change anything below, but make sure
### that the version of poi_id.py that you submit can be run on its own and
### generates the necessary .pkl files for validating your results.

dump_classifier_and_data(clf, my_dataset, features_list)

## Features

**financial features:** ['salary', 'deferral_payments', 'total_payments', 'loan_advances', 'bonus', 'restricted_stock_deferred', 'deferred_income', 'total_stock_value', 'expenses', 'exercised_stock_options', 'other', 'long_term_incentive', 'restricted_stock', 'director_fees']

(all units are in US dollars)

**email features:** ['to_messages', 'email_address', 'from_poi_to_this_person', 'from_messages', 'from_this_person_to_poi', 'shared_receipt_with_poi'] 

(units are generally number of emails messages; notable exception is ‘email_address’, which is a text string)

**POI label:** [‘poi’] (boolean, represented as integer)

## Tester

In [17]:
%run ./tester.py

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')
	Accuracy: 0.79540	Precision: 0.23421	Recall: 0.23550	F1: 0.23485	F2: 0.23524
	Total predictions: 15000	True positives:  471	False positives: 1540	False negatives: 1529	True negatives: 11460

